### ISSUE TITLE
help me！

### ISSUE THREAD

**Issue by lanjiachuan** [ethand91/mediasoup-ios-client-sample#1]
Excuse me, your project does not seem to support more than two people to participate in the meeting. Also, can you provide a set of flutter projects?

**Comment by ethand91** [comment]
> Excuse me, your project does not seem to support more than two people to participate in the meeting.

This project only demonstrates basic mediasoup features (publish/play etc.)
I might make it support more than 2 people when I get time, but at the moment you will need to implement it yourself. 

>Also, can you provide a set of flutter projects?

Sorry, never touched flutter however I may look into it.
