### ISSUE TITLE
What are the reasons why RecvTransportHandler does not execute the onConnect function

### ISSUE THREAD

**Issue by txyhost** [ethand91/mediasoup-ios-client-sample#3]

**Comment by txyhost** [comment]
Pictured
![1586325139201](https://user-images.githubusercontent.com/59674898/78749167-481fe700-79a0-11ea-8965-233fa91324dc.jpg)

**Comment by ethand91** [comment]
It runs on my device, if it doesn't I dont think you will be able to receive any remote stream.
Could you post the full logs?

**Comment by a42279395** [comment]
Thank you, it is my problem, has been solved.

**Comment by txyhost** [comment]
> 谢谢，这是我的问题，已经解决了。

咋解决的 兄弟

**Comment by a42279395** [comment]
Was I initialize the producer is not correct, my demo is different from his.

**Comment by txyhost** [comment]
> 我初始化制作人是否正确，我的演示与他的演示不同。

兄弟在哪个城市啊 有没有联系方式可以直接沟通 qq或者微信

**Comment by a42279395** [comment]
710041899 我的qq

**Comment by txyhost** [comment]
{"codecs":[{"rtcpFeedback":[{"parameter":"","type":"transport-cc"}],"mimeType":"audio/opus","preferredPayloadType":100,"clockRate":48000,"parameters":{},"channels":2,"kind":"audio"},{"rtcpFeedback":[{"parameter":"","type":"nack"},{"parameter":"pli","type":"nack"},{"parameter":"fir","type":"ccm"},{"parameter":"","type":"goog-remb"},{"parameter":"","type":"transport-cc"}],"mimeType":"video/VP8","preferredPayloadType":101,"clockRate":90000,"parameters":{"x-google-start-bitrate":1500},"channels":1,"kind":"video"},{"rtcpFeedback":[],"mimeType":"video/rtx","preferredPayloadType":102,"clockRate":90000,"parameters":{"apt":101},"channels":1,"kind":"video"}],"headerExtensions":[{"preferredEncrypt":false,"preferredId":1,"uri":"urn:ietf:params:rtp-hdrext:sdes:mid","kind":"audio","direction":"recvonly"},{"preferredEncrypt":false,"preferredId":1,"uri":"urn:ietf:params:rtp-hdrext:sdes:mid","kind":"video","direction":"recvonly"},{"preferredEncrypt":false,"preferredId":2,"uri":"urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id","kind":"video","direction":"recvonly"},{"preferredEncrypt":false,"preferredId":3,"uri":"urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id","kind":"video","direction":"recvonly"},{"preferredEncrypt":false,"preferredId":4,"uri":"http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time","kind":"audio","direction":"sendrecv"},{"preferredEncrypt":false,"preferredId":4,"uri":"http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time","kind":"video","direction":"sendrecv"},{"preferredEncrypt":false,"preferredId":5,"uri":"http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01","kind":"audio","direction":"recvonly"},{"preferredEncrypt":false,"preferredId":5,"uri":"http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01","kind":"video","direction":"sendrecv"},{"preferredEncrypt":false,"preferredId":6,"uri":"http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07","kind":"video","direction":"sendrecv"},{"preferredEncrypt":false,"preferredId":7,"uri":"urn:ietf:params:rtp-hdrext:framemarking","kind":"video","direction":"sendrecv"},{"preferredEncrypt":false,"preferredId":10,"uri":"urn:ietf:params:rtp-hdrext:ssrc-audio-level","kind":"audio","direction":"sendrecv"},{"preferredEncrypt":false,"preferredId":11,"uri":"urn:3gpp:video-orientation","kind":"video","direction":"sendrecv"},{"preferredEncrypt":false,"preferredId":12,"uri":"urn:ietf:params:rtp-hdrext:toffset","kind":"video","direction":"sendrecv"}]}

The data returned by my server getroomrtpcapabilitiesresponse
Is it related to this
