### ISSUE TITLE
The opening and closing of cameras

### ISSUE THREAD

**Issue by a42279395** [ethand91/mediasoup-ios-client-sample#6]
When I repeat to open, close the camera, could lead to a surge in memory.Should I open again, close the camera, how to correctly handle?

**Comment by ethand91** [comment]
Sorry for the late response.
when closing the camera, does setting the video capturer instance to nil help?

**Comment by a42279395** [comment]
Thanks for your reply, I have tried! But it didn't work.

**Comment by ethand91** [comment]
This may be an issue with the libwebrtc library, could you try checking there?
