### ISSUE TITLE
Websocket disconnect

### ISSUE THREAD

**Issue by venkatmacapp** [ethand91/mediasoup-ios-client-sample#7]
Always got error websocketDidDisconnect

**Comment by lihualin1688** [comment]
objc[27009]: Class RTCDispatcher is implemented in both /private/var/containers/Bundle/Application/3179CDB4-DF4F-4F15-9F3C-22BA41CBE094/mediasoup-ios-cient-sample.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x105bf9928) and /private/var/containers/Bundle/Application/3179CDB4-DF4F-4F15-9F3C-22BA41CBE094/mediasoup-ios-cient-sample.app/Frameworks/WebRTC.framework/WebRTC (0x1054e66c8). One of the two will be used. Which one is undefined.
objc[27009]: Class RTCCameraPreviewView is implemented in both /private/var/containers/Bundle/Application/3179CDB4-DF4F-4F15-9F3C-22BA41CBE094/mediasoup-ios-cient-sample.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x105bf9950) and /private/var/containers/Bundle/Application/3179CDB4-DF4F-4F15-9F3C-22BA41CBE094/mediasoup-ios-cient-sample.app/Frameworks/WebRTC.framework/WebRTC (0x1054e66f0). One of the two will be used. Which one is undefined.
objc[27009]: Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1e8c7aea0) and /private/var/containers/Bundle/Application/3179CDB4-DF4F-4F15-9F3C-22BA41CBE094/mediasoup-ios-cient-sample.app/Frameworks/WebRTC.framework/WebRTC (0x1054e67e0). One of the two will be used. Which one is undefined.
viewDidLoad()
websocketDidDisconnect

**Comment by ethand91** [comment]
Change the ip in the ViewController [connectWebSocket] to a server ip on the same network
