### ISSUE TITLE
How come I don't need to add the WebRTC binaries (libwebrtc.a, libmediasoupclient.a and libsdptransform.a) in the project?

### ISSUE THREAD

**Issue by xplatsolutions** [ethand91/mediasoup-ios-client-sample#9]
Hi,

Since I was building the WebRTC binaries from your [mediasoup-ios-client instructions](https://github.com/ethand91/mediasoup-ios-client/blob/master/build/mediasoup%403%20iOS%20WebRTC%20Framework%20Build%20Instructions.md) I'm a bit confused how come I just cloned this sample client and it's building, am I missing something where we don't need the enormous libwebrtc.a, libmediasoupclient.a and libsdptransform.a? See the screenshots below.

My project frameworks:
<img width="318" alt="Screen Shot 2020-06-23 at 04 37 52" src="https://user-images.githubusercontent.com/10971321/85380728-44b1eb80-b50b-11ea-9c80-573046e46b79.png">

Your project frameworks:
<img width="330" alt="Screen Shot 2020-06-23 at 04 38 16" src="https://user-images.githubusercontent.com/10971321/85380776-4f6c8080-b50b-11ea-83cc-67d7f287547c.png">

The next thing I noticed is that `SceneDelegate.swift` is removed from your workspace, nevertheless, while I have all frameworks in place I added `let device = Device.init();` in my project `SceneDelegate.swift` but I receive `Use of unresolved identifier 'Device'`.

**Comment by ethand91** [comment]
The static libraries are only needed to build the mediasoup ios client, you don't need to include them in your project.

>The next thing I noticed is that SceneDelegate.swift is removed from your workspace

This project doesn't use SwiftUI. Even though I set xCode to use storyboard it still creates it.. 
By removing it devices lower than iOS 13 can run the project.

For device you may needed to change your Framework Search Paths and Header File Paths, and possibly the bridging header.
To save headaches I'd recommend using the pod

**Comment by xplatsolutions** [comment]
OK got it, I actually went through the building instructions you have in case you don't want to use the `mediasoup_client_ios` pod, that was unnecessary for me :)

I guess it was confusing due to the part in [README.md](https://github.com/ethand91/mediasoup-ios-client/blob/master/README.md)
`Due to the size of the WebRTC.framework with bitcode, it cannot be uploaded to Github.`
So I started building it from the instructions.

Removed the binaries and building fine, but will still fail in `let device = Device.init();`

I have no problem requiring iOS 13 as minimum framework so I am OK with that.

Here's my bridging header:
<img width="858" alt="Screen Shot 2020-06-23 at 06 17 53" src="https://user-images.githubusercontent.com/10971321/85392220-3cf94380-b519-11ea-86a0-5027128cf94d.png">

Framework Search Paths:
<img width="903" alt="Screen Shot 2020-06-23 at 06 15 47" src="https://user-images.githubusercontent.com/10971321/85392007-f1469a00-b518-11ea-8d41-3cdc2912e0a7.png">

I added `$(PROJECT_DIR)/Frameworks` like you have in your sample client but still nothing, maybe the bridging header issue;

I can't seem to find where `Header File Paths` is located in project settings.

**Comment by ethand91** [comment]
>I guess it was confusing due to the part in README.md

I guess it is a bit misleading. I'll edit it :)

>I can't seem to find where Header File Paths is located in project settings.

Sorry meant Header Search Paths (target -> build settings)

**Comment by xplatsolutions** [comment]
Thanks, added $(inherited) but no improvement:
<img width="1177" alt="Screen Shot 2020-06-23 at 06 33 11" src="https://user-images.githubusercontent.com/10971321/85393659-5ef3c580-b51b-11ea-83b4-e29be02b61cf.png">

I checked your sample project when double click it shows $(inherited) but at the same time you have visual in framework headers:
<img width="1179" alt="Screen Shot 2020-06-23 at 06 34 19" src="https://user-images.githubusercontent.com/10971321/85393761-8480cf00-b51b-11ea-8b98-06d9832d40f2.png">

Is there anything special need for the bridging header? I just manually created the file same name with the project appending `-Bridging-Header` but other than that didn't add it to any settings or configuration.

**Comment by ethand91** [comment]
Could you try adding the below to your header search path
[Framework location]/mediasoup_client_ios.framework/Headers

**Comment by xplatsolutions** [comment]
Based on pwd command searching my path for the framework I get the below:
`/Users/georgiostaskos/Documents/Source_Zoe/Zoe.Phone/src/Zoe.Phone/Pods/mediasoup_ios_client/build`

Added to my project `Header Search Paths`:
`$(PODS_ROOT)/mediasoup_ios_client/build/mediasoup_client_ios.framework/Headers`
But no success so far...
<img width="1106" alt="Screen Shot 2020-06-23 at 06 56 37" src="https://user-images.githubusercontent.com/10971321/85395763-a62f8580-b51e-11ea-83d8-73306f59b028.png">

Here's the project structure:
<img width="318" alt="Screen Shot 2020-06-23 at 06 57 43" src="https://user-images.githubusercontent.com/10971321/85395860-c8c19e80-b51e-11ea-84f0-9ccfe4f64f75.png">

It looks like `Framework Search Paths` got it right;
<img width="1057" alt="Screen Shot 2020-06-23 at 06 58 32" src="https://user-images.githubusercontent.com/10971321/85395935-e68f0380-b51e-11ea-8fc9-6d690f5efc85.png">

Your help is valuable in this new project bootstrap :) it's always tough in the beginning!

**Comment by xplatsolutions** [comment]
Project is building, I haven't added the `Objective-C Bridging Header` to the bridging header path :/

Thanks for your support, I am closing this issue.
